### ISSUE TITLE
ConsoleKey

### ISSUE THREAD

**Issue by wadefisher** [NVentimiglia/TDAmeritrade.DotNetCore#2]
Using Visual Studio on Window 10
Microsoft Visual Studio Community 2019
Version 16.9.4

TDAmeritrade.Console : Main
Line 34
\   case ConsoleKey.NumPad1: //.D1
I had to switch out the "D1" for "NumPad1" to get it to read the console input.

What am I missing?

**Comment by wadefisher** [comment]
I see now.... Sorry new to C#.   The Numpad reads different from the D1.  I will add both to the code.

**Comment by NVentimiglia** [comment]
Ill include a fix for this in the next release
