### ISSUE TITLE
A third-party application may be attempting to make unauthorized access to your account.

### ISSUE THREAD

**Issue by srinall** [NVentimiglia/TDAmeritrade.DotNetCore#3]
I am failing to get code from the url "https://auth.tdameritrade.com/auth?response_type=code&redirect_uri=http%3a%2f%2flocalhost&client_id=XXXXXXXXX%40AMER.OAUTHAP"

I get the following error message. Anything I need to do here to unblock myself? Thanks much!

"A third-party application may be attempting to make unauthorized access to your account. For help with your account, contact us. For information on securing your account, visit the TD Ameritrade Security page."

**Comment by srinall** [comment]
I was able to resolve the above issue by configuring the call back url to "http://localhost".

**Comment by arielhammon** [comment]
I encountered this and another error with the callback (redirect) url set to "http://localhost" in TDAmeritradeClient.cs in both the GetSignInUrl and SignIn methods. Everything seemed to work fine by changing both strings to "https://localhost".
