### ISSUE TITLE
Request QOS

### ISSUE THREAD

**Issue by wadefisher** [NVentimiglia/TDAmeritrade.DotNetCore#6]
In - TDAmeritradeStreamClient.cs   Line: 404:  "command = SUBS">
I believe this is giving the return error: {"response":[{"service":"ADMIN","requestid":"2","command":"SUBS","timestamp":1631545823396,"content":{"code":21,"msg":**"Bad command formatting**"}}]}

When I change it to "QOS" (command = "QOS") it returns: 
{"response":[{"service":"ADMIN","requestid":"2","command":"QOS","timestamp":1631540977902,"content":{"code":0,"msg":"QoS **command succeeded.** Set qoslevel=3"}}]}

TD Ameritrade user guide:
![Screenshot 2021-09-13 112002](https://user-images.githubusercontent.com/47784668/133111150-83d54301-cb55-4602-8a94-93aae04d75e2.png)

I am a nub at C# so please forgive me if I am wrong.

**Comment by wadefisher** [comment]
I should add: This is using the TDAmeritrade.Console test app. to generate the return codes.

**Comment by NVentimiglia** [comment]
Great Catch!

If you want to make a PR with the fix, Ill accept. Else I will make one tonight.

**Comment by wadefisher** [comment]
You better.  I am just starting to use GitHub
